// Autogenerated from Pigeon (v22.7.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Any?

  init(code: String, message: String?, details: Any?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
      }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

/// Object-detector categories (match the native SDK's class order).
enum NosmaiCategory: Int {
  case weapon = 0
  case drug = 1
  case cigarette = 2
  case alcohol = 3
}

/// Whole-image NSFW verdict. `block` makes a frame unsafe; `warn` (suggestive)
/// is advisory only.
enum NosmaiNsfwVerdict: Int {
  case safe = 0
  case warn = 1
  case block = 2
}

/// NSFW classes used by [NosmaiModerationApi.setNsfwThreshold].
enum NosmaiNsfwClass: Int {
  case explicit = 0
  case safe = 1
  case sexy = 2
}

/// Chat-text moderation categories.
enum NosmaiTextCategory: Int {
  case safe = 0
  case profanity = 1
  case toxic = 2
  case hate = 3
  case harassment = 4
  case threat = 5
}

/// Which text layer produced the verdict.
enum NosmaiTextLayer: Int {
  case none = 0
  case blocklist = 1
  case classifier = 2
}

/// Models that can be loaded at [NosmaiModerationApi.initialize]. Only the models
/// you pass are loaded; anything omitted never loads.
enum NosmaiModel: Int {
  case objectDetection = 0
  case nsfw = 1
  case text = 2
}

/// Generated class from Pigeon that represents data sent in messages.
struct NosmaiObjectDetection {
  var category: NosmaiCategory? = nil
  var confidence: Double? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> NosmaiObjectDetection? {
    let category: NosmaiCategory? = nilOrValue(pigeonVar_list[0])
    let confidence: Double? = nilOrValue(pigeonVar_list[1])

    return NosmaiObjectDetection(
      category: category,
      confidence: confidence
    )
  }
  func toList() -> [Any?] {
    return [
      category,
      confidence,
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct NosmaiResult {
  var isUnsafe: Bool? = nil
  var detections: [NosmaiObjectDetection?]? = nil
  var nsfw: NosmaiNsfwVerdict? = nil
  var nsfwSafe: Double? = nil
  var nsfwSexy: Double? = nil
  var nsfwExplicit: Double? = nil
  var rawWeapon: Double? = nil
  var rawDrug: Double? = nil
  var rawCigarette: Double? = nil
  var rawAlcohol: Double? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> NosmaiResult? {
    let isUnsafe: Bool? = nilOrValue(pigeonVar_list[0])
    let detections: [NosmaiObjectDetection?]? = nilOrValue(pigeonVar_list[1])
    let nsfw: NosmaiNsfwVerdict? = nilOrValue(pigeonVar_list[2])
    let nsfwSafe: Double? = nilOrValue(pigeonVar_list[3])
    let nsfwSexy: Double? = nilOrValue(pigeonVar_list[4])
    let nsfwExplicit: Double? = nilOrValue(pigeonVar_list[5])
    let rawWeapon: Double? = nilOrValue(pigeonVar_list[6])
    let rawDrug: Double? = nilOrValue(pigeonVar_list[7])
    let rawCigarette: Double? = nilOrValue(pigeonVar_list[8])
    let rawAlcohol: Double? = nilOrValue(pigeonVar_list[9])

    return NosmaiResult(
      isUnsafe: isUnsafe,
      detections: detections,
      nsfw: nsfw,
      nsfwSafe: nsfwSafe,
      nsfwSexy: nsfwSexy,
      nsfwExplicit: nsfwExplicit,
      rawWeapon: rawWeapon,
      rawDrug: rawDrug,
      rawCigarette: rawCigarette,
      rawAlcohol: rawAlcohol
    )
  }
  func toList() -> [Any?] {
    return [
      isUnsafe,
      detections,
      nsfw,
      nsfwSafe,
      nsfwSexy,
      nsfwExplicit,
      rawWeapon,
      rawDrug,
      rawCigarette,
      rawAlcohol,
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct NosmaiVideoFlag {
  var timestampMs: Int64? = nil
  var category: NosmaiCategory? = nil
  var confidence: Double? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> NosmaiVideoFlag? {
    let timestampMs: Int64? = nilOrValue(pigeonVar_list[0])
    let category: NosmaiCategory? = nilOrValue(pigeonVar_list[1])
    let confidence: Double? = nilOrValue(pigeonVar_list[2])

    return NosmaiVideoFlag(
      timestampMs: timestampMs,
      category: category,
      confidence: confidence
    )
  }
  func toList() -> [Any?] {
    return [
      timestampMs,
      category,
      confidence,
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct NosmaiVideoResult {
  var isUnsafe: Bool? = nil
  var categories: [NosmaiCategory?]? = nil
  var flags: [NosmaiVideoFlag?]? = nil
  var framesAnalyzed: Int64? = nil
  var nsfw: NosmaiNsfwVerdict? = nil
  var nsfwFlaggedMs: [Int64?]? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> NosmaiVideoResult? {
    let isUnsafe: Bool? = nilOrValue(pigeonVar_list[0])
    let categories: [NosmaiCategory?]? = nilOrValue(pigeonVar_list[1])
    let flags: [NosmaiVideoFlag?]? = nilOrValue(pigeonVar_list[2])
    let framesAnalyzed: Int64? = nilOrValue(pigeonVar_list[3])
    let nsfw: NosmaiNsfwVerdict? = nilOrValue(pigeonVar_list[4])
    let nsfwFlaggedMs: [Int64?]? = nilOrValue(pigeonVar_list[5])

    return NosmaiVideoResult(
      isUnsafe: isUnsafe,
      categories: categories,
      flags: flags,
      framesAnalyzed: framesAnalyzed,
      nsfw: nsfw,
      nsfwFlaggedMs: nsfwFlaggedMs
    )
  }
  func toList() -> [Any?] {
    return [
      isUnsafe,
      categories,
      flags,
      framesAnalyzed,
      nsfw,
      nsfwFlaggedMs,
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct NosmaiTextResult {
  var blocked: Bool? = nil
  var layer: NosmaiTextLayer? = nil
  var category: NosmaiTextCategory? = nil
  var score: Double? = nil
  var matchedWord: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> NosmaiTextResult? {
    let blocked: Bool? = nilOrValue(pigeonVar_list[0])
    let layer: NosmaiTextLayer? = nilOrValue(pigeonVar_list[1])
    let category: NosmaiTextCategory? = nilOrValue(pigeonVar_list[2])
    let score: Double? = nilOrValue(pigeonVar_list[3])
    let matchedWord: String? = nilOrValue(pigeonVar_list[4])

    return NosmaiTextResult(
      blocked: blocked,
      layer: layer,
      category: category,
      score: score,
      matchedWord: matchedWord
    )
  }
  func toList() -> [Any?] {
    return [
      blocked,
      layer,
      category,
      score,
      matchedWord,
    ]
  }
}

/// Result of [NosmaiModerationApi.initialize] — `success` plus an `error`
/// message (e.g. license invalid / expired) when it fails.
///
/// Generated class from Pigeon that represents data sent in messages.
struct NosmaiInitResult {
  var success: Bool? = nil
  var error: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> NosmaiInitResult? {
    let success: Bool? = nilOrValue(pigeonVar_list[0])
    let error: String? = nilOrValue(pigeonVar_list[1])

    return NosmaiInitResult(
      success: success,
      error: error
    )
  }
  func toList() -> [Any?] {
    return [
      success,
      error,
    ]
  }
}

private class MessagesPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return NosmaiCategory(rawValue: enumResultAsInt)
      }
      return nil
    case 130:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return NosmaiNsfwVerdict(rawValue: enumResultAsInt)
      }
      return nil
    case 131:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return NosmaiNsfwClass(rawValue: enumResultAsInt)
      }
      return nil
    case 132:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return NosmaiTextCategory(rawValue: enumResultAsInt)
      }
      return nil
    case 133:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return NosmaiTextLayer(rawValue: enumResultAsInt)
      }
      return nil
    case 134:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return NosmaiModel(rawValue: enumResultAsInt)
      }
      return nil
    case 135:
      return NosmaiObjectDetection.fromList(self.readValue() as! [Any?])
    case 136:
      return NosmaiResult.fromList(self.readValue() as! [Any?])
    case 137:
      return NosmaiVideoFlag.fromList(self.readValue() as! [Any?])
    case 138:
      return NosmaiVideoResult.fromList(self.readValue() as! [Any?])
    case 139:
      return NosmaiTextResult.fromList(self.readValue() as! [Any?])
    case 140:
      return NosmaiInitResult.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class MessagesPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? NosmaiCategory {
      super.writeByte(129)
      super.writeValue(value.rawValue)
    } else if let value = value as? NosmaiNsfwVerdict {
      super.writeByte(130)
      super.writeValue(value.rawValue)
    } else if let value = value as? NosmaiNsfwClass {
      super.writeByte(131)
      super.writeValue(value.rawValue)
    } else if let value = value as? NosmaiTextCategory {
      super.writeByte(132)
      super.writeValue(value.rawValue)
    } else if let value = value as? NosmaiTextLayer {
      super.writeByte(133)
      super.writeValue(value.rawValue)
    } else if let value = value as? NosmaiModel {
      super.writeByte(134)
      super.writeValue(value.rawValue)
    } else if let value = value as? NosmaiObjectDetection {
      super.writeByte(135)
      super.writeValue(value.toList())
    } else if let value = value as? NosmaiResult {
      super.writeByte(136)
      super.writeValue(value.toList())
    } else if let value = value as? NosmaiVideoFlag {
      super.writeByte(137)
      super.writeValue(value.toList())
    } else if let value = value as? NosmaiVideoResult {
      super.writeByte(138)
      super.writeValue(value.toList())
    } else if let value = value as? NosmaiTextResult {
      super.writeByte(139)
      super.writeValue(value.toList())
    } else if let value = value as? NosmaiInitResult {
      super.writeByte(140)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class MessagesPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return MessagesPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return MessagesPigeonCodecWriter(data: data)
  }
}

class MessagesPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = MessagesPigeonCodec(readerWriter: MessagesPigeonCodecReaderWriter())
}


/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol NosmaiModerationApi {
  /// Validates the license and loads ONLY the requested [models]. A model you do
  /// not pass never loads. Runs on a background thread natively.
  func initialize(licenseKey: String, models: [NosmaiModel], completion: @escaping (Result<NosmaiInitResult, Error>) -> Void)
  /// Loads the chat text-moderation model. Optional — call only if you moderate
  /// text.
  func initializeText(completion: @escaping (Result<Bool, Error>) -> Void)
  /// Moderates a single image file (objects + NSFW).
  func analyzeImage(filePath: String, completion: @escaping (Result<NosmaiResult, Error>) -> Void)
  /// Moderates a recorded video, sampling one frame per [frameIntervalMs].
  func analyzeVideo(filePath: String, frameIntervalMs: Int64, completion: @escaping (Result<NosmaiVideoResult, Error>) -> Void)
  /// Moderates a chat message (Layer-1 blocklist + Layer-2 toxicity model).
  func moderateText(message: String, completion: @escaping (Result<NosmaiTextResult, Error>) -> Void)
  /// Overrides an object-detector confidence threshold (0..1).
  func setThreshold(category: NosmaiCategory, value: Double) throws
  /// Overrides an NSFW decision threshold (explicit -> BLOCK, sexy -> WARN).
  func setNsfwThreshold(nsfwClass: NosmaiNsfwClass, value: Double) throws
  /// Releases the engine and frees memory.
  func shutdown() throws
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class NosmaiModerationApiSetup {
  static var codec: FlutterStandardMessageCodec { MessagesPigeonCodec.shared }
  /// Sets up an instance of `NosmaiModerationApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: NosmaiModerationApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    /// Validates the license and loads ONLY the requested [models]. A model you do
    /// not pass never loads. Runs on a background thread natively.
    let initializeChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.nosmai_moderation_sdk.NosmaiModerationApi.initialize\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      initializeChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let licenseKeyArg = args[0] as! String
        let modelsArg = args[1] as! [NosmaiModel]
        api.initialize(licenseKey: licenseKeyArg, models: modelsArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      initializeChannel.setMessageHandler(nil)
    }
    /// Loads the chat text-moderation model. Optional — call only if you moderate
    /// text.
    let initializeTextChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.nosmai_moderation_sdk.NosmaiModerationApi.initializeText\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      initializeTextChannel.setMessageHandler { _, reply in
        api.initializeText { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      initializeTextChannel.setMessageHandler(nil)
    }
    /// Moderates a single image file (objects + NSFW).
    let analyzeImageChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.nosmai_moderation_sdk.NosmaiModerationApi.analyzeImage\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      analyzeImageChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let filePathArg = args[0] as! String
        api.analyzeImage(filePath: filePathArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      analyzeImageChannel.setMessageHandler(nil)
    }
    /// Moderates a recorded video, sampling one frame per [frameIntervalMs].
    let analyzeVideoChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.nosmai_moderation_sdk.NosmaiModerationApi.analyzeVideo\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      analyzeVideoChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let filePathArg = args[0] as! String
        let frameIntervalMsArg = args[1] as! Int64
        api.analyzeVideo(filePath: filePathArg, frameIntervalMs: frameIntervalMsArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      analyzeVideoChannel.setMessageHandler(nil)
    }
    /// Moderates a chat message (Layer-1 blocklist + Layer-2 toxicity model).
    let moderateTextChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.nosmai_moderation_sdk.NosmaiModerationApi.moderateText\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      moderateTextChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let messageArg = args[0] as! String
        api.moderateText(message: messageArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      moderateTextChannel.setMessageHandler(nil)
    }
    /// Overrides an object-detector confidence threshold (0..1).
    let setThresholdChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.nosmai_moderation_sdk.NosmaiModerationApi.setThreshold\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setThresholdChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let categoryArg = args[0] as! NosmaiCategory
        let valueArg = args[1] as! Double
        do {
          try api.setThreshold(category: categoryArg, value: valueArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setThresholdChannel.setMessageHandler(nil)
    }
    /// Overrides an NSFW decision threshold (explicit -> BLOCK, sexy -> WARN).
    let setNsfwThresholdChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.nosmai_moderation_sdk.NosmaiModerationApi.setNsfwThreshold\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setNsfwThresholdChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let nsfwClassArg = args[0] as! NosmaiNsfwClass
        let valueArg = args[1] as! Double
        do {
          try api.setNsfwThreshold(nsfwClass: nsfwClassArg, value: valueArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setNsfwThresholdChannel.setMessageHandler(nil)
    }
    /// Releases the engine and frees memory.
    let shutdownChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.nosmai_moderation_sdk.NosmaiModerationApi.shutdown\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      shutdownChannel.setMessageHandler { _, reply in
        do {
          try api.shutdown()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      shutdownChannel.setMessageHandler(nil)
    }
  }
}
