// Autogenerated from Pigeon (v22.7.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: public_member_api_docs, non_constant_identifier_names, avoid_as, unused_import, unnecessary_parenthesis, prefer_null_aware_operators, omit_local_variable_types, unused_shown_name, unnecessary_import, no_leading_underscores_for_local_identifiers

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List, Uint8List;

import 'package:flutter/foundation.dart' show ReadBuffer, WriteBuffer;
import 'package:flutter/services.dart';

PlatformException _createConnectionError(String channelName) {
  return PlatformException(
    code: 'channel-error',
    message: 'Unable to establish connection on channel: "$channelName".',
  );
}

/// Object-detector categories (match the native SDK's class order).
enum NosmaiCategory {
  weapon,
  drug,
  cigarette,
  alcohol,
}

/// Whole-image NSFW verdict. `block` makes a frame unsafe; `warn` (suggestive)
/// is advisory only.
enum NosmaiNsfwVerdict {
  safe,
  warn,
  block,
}

/// NSFW classes used by [NosmaiModerationApi.setNsfwThreshold].
enum NosmaiNsfwClass {
  explicit,
  safe,
  sexy,
}

/// Chat-text moderation categories.
enum NosmaiTextCategory {
  safe,
  profanity,
  toxic,
  hate,
  harassment,
  threat,
}

/// Which text layer produced the verdict.
enum NosmaiTextLayer {
  none,
  blocklist,
  classifier,
}

/// Models that can be loaded at [NosmaiModerationApi.initialize]. Only the models
/// you pass are loaded; anything omitted never loads.
enum NosmaiModel {
  objectDetection,
  nsfw,
  text,
}

class NosmaiObjectDetection {
  NosmaiObjectDetection({
    this.category,
    this.confidence,
  });

  NosmaiCategory? category;

  double? confidence;

  Object encode() {
    return <Object?>[
      category,
      confidence,
    ];
  }

  static NosmaiObjectDetection decode(Object result) {
    result as List<Object?>;
    return NosmaiObjectDetection(
      category: result[0] as NosmaiCategory?,
      confidence: result[1] as double?,
    );
  }
}

class NosmaiResult {
  NosmaiResult({
    this.isUnsafe,
    this.detections,
    this.nsfw,
    this.nsfwSafe,
    this.nsfwSexy,
    this.nsfwExplicit,
    this.rawWeapon,
    this.rawDrug,
    this.rawCigarette,
    this.rawAlcohol,
  });

  bool? isUnsafe;

  List<NosmaiObjectDetection?>? detections;

  NosmaiNsfwVerdict? nsfw;

  double? nsfwSafe;

  double? nsfwSexy;

  double? nsfwExplicit;

  double? rawWeapon;

  double? rawDrug;

  double? rawCigarette;

  double? rawAlcohol;

  Object encode() {
    return <Object?>[
      isUnsafe,
      detections,
      nsfw,
      nsfwSafe,
      nsfwSexy,
      nsfwExplicit,
      rawWeapon,
      rawDrug,
      rawCigarette,
      rawAlcohol,
    ];
  }

  static NosmaiResult decode(Object result) {
    result as List<Object?>;
    return NosmaiResult(
      isUnsafe: result[0] as bool?,
      detections: (result[1] as List<Object?>?)?.cast<NosmaiObjectDetection?>(),
      nsfw: result[2] as NosmaiNsfwVerdict?,
      nsfwSafe: result[3] as double?,
      nsfwSexy: result[4] as double?,
      nsfwExplicit: result[5] as double?,
      rawWeapon: result[6] as double?,
      rawDrug: result[7] as double?,
      rawCigarette: result[8] as double?,
      rawAlcohol: result[9] as double?,
    );
  }
}

class NosmaiVideoFlag {
  NosmaiVideoFlag({
    this.timestampMs,
    this.category,
    this.confidence,
  });

  int? timestampMs;

  NosmaiCategory? category;

  double? confidence;

  Object encode() {
    return <Object?>[
      timestampMs,
      category,
      confidence,
    ];
  }

  static NosmaiVideoFlag decode(Object result) {
    result as List<Object?>;
    return NosmaiVideoFlag(
      timestampMs: result[0] as int?,
      category: result[1] as NosmaiCategory?,
      confidence: result[2] as double?,
    );
  }
}

class NosmaiVideoResult {
  NosmaiVideoResult({
    this.isUnsafe,
    this.categories,
    this.flags,
    this.framesAnalyzed,
    this.nsfw,
    this.nsfwFlaggedMs,
  });

  bool? isUnsafe;

  List<NosmaiCategory?>? categories;

  List<NosmaiVideoFlag?>? flags;

  int? framesAnalyzed;

  NosmaiNsfwVerdict? nsfw;

  List<int?>? nsfwFlaggedMs;

  Object encode() {
    return <Object?>[
      isUnsafe,
      categories,
      flags,
      framesAnalyzed,
      nsfw,
      nsfwFlaggedMs,
    ];
  }

  static NosmaiVideoResult decode(Object result) {
    result as List<Object?>;
    return NosmaiVideoResult(
      isUnsafe: result[0] as bool?,
      categories: (result[1] as List<Object?>?)?.cast<NosmaiCategory?>(),
      flags: (result[2] as List<Object?>?)?.cast<NosmaiVideoFlag?>(),
      framesAnalyzed: result[3] as int?,
      nsfw: result[4] as NosmaiNsfwVerdict?,
      nsfwFlaggedMs: (result[5] as List<Object?>?)?.cast<int?>(),
    );
  }
}

class NosmaiTextResult {
  NosmaiTextResult({
    this.blocked,
    this.layer,
    this.category,
    this.score,
    this.matchedWord,
  });

  bool? blocked;

  NosmaiTextLayer? layer;

  NosmaiTextCategory? category;

  double? score;

  String? matchedWord;

  Object encode() {
    return <Object?>[
      blocked,
      layer,
      category,
      score,
      matchedWord,
    ];
  }

  static NosmaiTextResult decode(Object result) {
    result as List<Object?>;
    return NosmaiTextResult(
      blocked: result[0] as bool?,
      layer: result[1] as NosmaiTextLayer?,
      category: result[2] as NosmaiTextCategory?,
      score: result[3] as double?,
      matchedWord: result[4] as String?,
    );
  }
}

/// Result of [NosmaiModerationApi.initialize] — `success` plus an `error`
/// message (e.g. license invalid / expired) when it fails.
class NosmaiInitResult {
  NosmaiInitResult({
    this.success,
    this.error,
  });

  bool? success;

  String? error;

  Object encode() {
    return <Object?>[
      success,
      error,
    ];
  }

  static NosmaiInitResult decode(Object result) {
    result as List<Object?>;
    return NosmaiInitResult(
      success: result[0] as bool?,
      error: result[1] as String?,
    );
  }
}


class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    }    else if (value is NosmaiCategory) {
      buffer.putUint8(129);
      writeValue(buffer, value.index);
    }    else if (value is NosmaiNsfwVerdict) {
      buffer.putUint8(130);
      writeValue(buffer, value.index);
    }    else if (value is NosmaiNsfwClass) {
      buffer.putUint8(131);
      writeValue(buffer, value.index);
    }    else if (value is NosmaiTextCategory) {
      buffer.putUint8(132);
      writeValue(buffer, value.index);
    }    else if (value is NosmaiTextLayer) {
      buffer.putUint8(133);
      writeValue(buffer, value.index);
    }    else if (value is NosmaiModel) {
      buffer.putUint8(134);
      writeValue(buffer, value.index);
    }    else if (value is NosmaiObjectDetection) {
      buffer.putUint8(135);
      writeValue(buffer, value.encode());
    }    else if (value is NosmaiResult) {
      buffer.putUint8(136);
      writeValue(buffer, value.encode());
    }    else if (value is NosmaiVideoFlag) {
      buffer.putUint8(137);
      writeValue(buffer, value.encode());
    }    else if (value is NosmaiVideoResult) {
      buffer.putUint8(138);
      writeValue(buffer, value.encode());
    }    else if (value is NosmaiTextResult) {
      buffer.putUint8(139);
      writeValue(buffer, value.encode());
    }    else if (value is NosmaiInitResult) {
      buffer.putUint8(140);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129: 
        final int? value = readValue(buffer) as int?;
        return value == null ? null : NosmaiCategory.values[value];
      case 130: 
        final int? value = readValue(buffer) as int?;
        return value == null ? null : NosmaiNsfwVerdict.values[value];
      case 131: 
        final int? value = readValue(buffer) as int?;
        return value == null ? null : NosmaiNsfwClass.values[value];
      case 132: 
        final int? value = readValue(buffer) as int?;
        return value == null ? null : NosmaiTextCategory.values[value];
      case 133: 
        final int? value = readValue(buffer) as int?;
        return value == null ? null : NosmaiTextLayer.values[value];
      case 134: 
        final int? value = readValue(buffer) as int?;
        return value == null ? null : NosmaiModel.values[value];
      case 135: 
        return NosmaiObjectDetection.decode(readValue(buffer)!);
      case 136: 
        return NosmaiResult.decode(readValue(buffer)!);
      case 137: 
        return NosmaiVideoFlag.decode(readValue(buffer)!);
      case 138: 
        return NosmaiVideoResult.decode(readValue(buffer)!);
      case 139: 
        return NosmaiTextResult.decode(readValue(buffer)!);
      case 140: 
        return NosmaiInitResult.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

class NosmaiModerationApi {
  /// Constructor for [NosmaiModerationApi].  The [binaryMessenger] named argument is
  /// available for dependency injection.  If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  NosmaiModerationApi({BinaryMessenger? binaryMessenger, String messageChannelSuffix = ''})
      : pigeonVar_binaryMessenger = binaryMessenger,
        pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  /// Validates the license and loads ONLY the requested [models]. A model you do
  /// not pass never loads. Runs on a background thread natively.
  Future<NosmaiInitResult> initialize(String licenseKey, List<NosmaiModel> models) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.nosmai_moderation_sdk.NosmaiModerationApi.initialize$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[licenseKey, models]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as NosmaiInitResult?)!;
    }
  }

  /// Loads the chat text-moderation model. Optional — call only if you moderate
  /// text.
  Future<bool> initializeText() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.nosmai_moderation_sdk.NosmaiModerationApi.initializeText$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(null) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as bool?)!;
    }
  }

  /// Moderates a single image file (objects + NSFW).
  Future<NosmaiResult> analyzeImage(String filePath) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.nosmai_moderation_sdk.NosmaiModerationApi.analyzeImage$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[filePath]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as NosmaiResult?)!;
    }
  }

  /// Moderates a recorded video, sampling one frame per [frameIntervalMs].
  Future<NosmaiVideoResult> analyzeVideo(String filePath, int frameIntervalMs) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.nosmai_moderation_sdk.NosmaiModerationApi.analyzeVideo$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[filePath, frameIntervalMs]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as NosmaiVideoResult?)!;
    }
  }

  /// Moderates a chat message (Layer-1 blocklist + Layer-2 toxicity model).
  Future<NosmaiTextResult> moderateText(String message) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.nosmai_moderation_sdk.NosmaiModerationApi.moderateText$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[message]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as NosmaiTextResult?)!;
    }
  }

  /// Overrides an object-detector confidence threshold (0..1).
  Future<void> setThreshold(NosmaiCategory category, double value) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.nosmai_moderation_sdk.NosmaiModerationApi.setThreshold$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[category, value]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  /// Overrides an NSFW decision threshold (explicit -> BLOCK, sexy -> WARN).
  Future<void> setNsfwThreshold(NosmaiNsfwClass nsfwClass, double value) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.nosmai_moderation_sdk.NosmaiModerationApi.setNsfwThreshold$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[nsfwClass, value]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  /// Releases the engine and frees memory.
  Future<void> shutdown() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.nosmai_moderation_sdk.NosmaiModerationApi.shutdown$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(null) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }
}
