// Autogenerated from Pigeon (v22.7.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package com.nosmai.nosmai_moderation_sdk

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer

private fun wrapResult(result: Any?): List<Any?> {
  return listOf(result)
}

private fun wrapError(exception: Throwable): List<Any?> {
  return if (exception is FlutterError) {
    listOf(
      exception.code,
      exception.message,
      exception.details
    )
  } else {
    listOf(
      exception.javaClass.simpleName,
      exception.toString(),
      "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
    )
  }
}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : Throwable()

/** Object-detector categories (match the native SDK's class order). */
enum class NosmaiCategory(val raw: Int) {
  WEAPON(0),
  DRUG(1),
  CIGARETTE(2),
  ALCOHOL(3);

  companion object {
    fun ofRaw(raw: Int): NosmaiCategory? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/**
 * Whole-image NSFW verdict. `block` makes a frame unsafe; `warn` (suggestive)
 * is advisory only.
 */
enum class NosmaiNsfwVerdict(val raw: Int) {
  SAFE(0),
  WARN(1),
  BLOCK(2);

  companion object {
    fun ofRaw(raw: Int): NosmaiNsfwVerdict? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/** NSFW classes used by [NosmaiModerationApi.setNsfwThreshold]. */
enum class NosmaiNsfwClass(val raw: Int) {
  EXPLICIT(0),
  SAFE(1),
  SEXY(2);

  companion object {
    fun ofRaw(raw: Int): NosmaiNsfwClass? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/** Chat-text moderation categories. */
enum class NosmaiTextCategory(val raw: Int) {
  SAFE(0),
  PROFANITY(1),
  TOXIC(2),
  HATE(3),
  HARASSMENT(4),
  THREAT(5);

  companion object {
    fun ofRaw(raw: Int): NosmaiTextCategory? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/** Which text layer produced the verdict. */
enum class NosmaiTextLayer(val raw: Int) {
  NONE(0),
  BLOCKLIST(1),
  CLASSIFIER(2);

  companion object {
    fun ofRaw(raw: Int): NosmaiTextLayer? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/**
 * Models that can be loaded at [NosmaiModerationApi.initialize]. Only the models
 * you pass are loaded; anything omitted never loads.
 */
enum class NosmaiModel(val raw: Int) {
  OBJECT_DETECTION(0),
  NSFW(1),
  TEXT(2);

  companion object {
    fun ofRaw(raw: Int): NosmaiModel? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class NosmaiObjectDetection (
  val category: NosmaiCategory? = null,
  val confidence: Double? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): NosmaiObjectDetection {
      val category = pigeonVar_list[0] as NosmaiCategory?
      val confidence = pigeonVar_list[1] as Double?
      return NosmaiObjectDetection(category, confidence)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      category,
      confidence,
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class NosmaiResult (
  val isUnsafe: Boolean? = null,
  val detections: List<NosmaiObjectDetection?>? = null,
  val nsfw: NosmaiNsfwVerdict? = null,
  val nsfwSafe: Double? = null,
  val nsfwSexy: Double? = null,
  val nsfwExplicit: Double? = null,
  val rawWeapon: Double? = null,
  val rawDrug: Double? = null,
  val rawCigarette: Double? = null,
  val rawAlcohol: Double? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): NosmaiResult {
      val isUnsafe = pigeonVar_list[0] as Boolean?
      val detections = pigeonVar_list[1] as List<NosmaiObjectDetection?>?
      val nsfw = pigeonVar_list[2] as NosmaiNsfwVerdict?
      val nsfwSafe = pigeonVar_list[3] as Double?
      val nsfwSexy = pigeonVar_list[4] as Double?
      val nsfwExplicit = pigeonVar_list[5] as Double?
      val rawWeapon = pigeonVar_list[6] as Double?
      val rawDrug = pigeonVar_list[7] as Double?
      val rawCigarette = pigeonVar_list[8] as Double?
      val rawAlcohol = pigeonVar_list[9] as Double?
      return NosmaiResult(isUnsafe, detections, nsfw, nsfwSafe, nsfwSexy, nsfwExplicit, rawWeapon, rawDrug, rawCigarette, rawAlcohol)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      isUnsafe,
      detections,
      nsfw,
      nsfwSafe,
      nsfwSexy,
      nsfwExplicit,
      rawWeapon,
      rawDrug,
      rawCigarette,
      rawAlcohol,
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class NosmaiVideoFlag (
  val timestampMs: Long? = null,
  val category: NosmaiCategory? = null,
  val confidence: Double? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): NosmaiVideoFlag {
      val timestampMs = pigeonVar_list[0] as Long?
      val category = pigeonVar_list[1] as NosmaiCategory?
      val confidence = pigeonVar_list[2] as Double?
      return NosmaiVideoFlag(timestampMs, category, confidence)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      timestampMs,
      category,
      confidence,
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class NosmaiVideoResult (
  val isUnsafe: Boolean? = null,
  val categories: List<NosmaiCategory?>? = null,
  val flags: List<NosmaiVideoFlag?>? = null,
  val framesAnalyzed: Long? = null,
  val nsfw: NosmaiNsfwVerdict? = null,
  val nsfwFlaggedMs: List<Long?>? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): NosmaiVideoResult {
      val isUnsafe = pigeonVar_list[0] as Boolean?
      val categories = pigeonVar_list[1] as List<NosmaiCategory?>?
      val flags = pigeonVar_list[2] as List<NosmaiVideoFlag?>?
      val framesAnalyzed = pigeonVar_list[3] as Long?
      val nsfw = pigeonVar_list[4] as NosmaiNsfwVerdict?
      val nsfwFlaggedMs = pigeonVar_list[5] as List<Long?>?
      return NosmaiVideoResult(isUnsafe, categories, flags, framesAnalyzed, nsfw, nsfwFlaggedMs)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      isUnsafe,
      categories,
      flags,
      framesAnalyzed,
      nsfw,
      nsfwFlaggedMs,
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class NosmaiTextResult (
  val blocked: Boolean? = null,
  val layer: NosmaiTextLayer? = null,
  val category: NosmaiTextCategory? = null,
  val score: Double? = null,
  val matchedWord: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): NosmaiTextResult {
      val blocked = pigeonVar_list[0] as Boolean?
      val layer = pigeonVar_list[1] as NosmaiTextLayer?
      val category = pigeonVar_list[2] as NosmaiTextCategory?
      val score = pigeonVar_list[3] as Double?
      val matchedWord = pigeonVar_list[4] as String?
      return NosmaiTextResult(blocked, layer, category, score, matchedWord)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      blocked,
      layer,
      category,
      score,
      matchedWord,
    )
  }
}

/**
 * Result of [NosmaiModerationApi.initialize] — `success` plus an `error`
 * message (e.g. license invalid / expired) when it fails.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class NosmaiInitResult (
  val success: Boolean? = null,
  val error: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): NosmaiInitResult {
      val success = pigeonVar_list[0] as Boolean?
      val error = pigeonVar_list[1] as String?
      return NosmaiInitResult(success, error)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      success,
      error,
    )
  }
}
private open class MessagesPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          NosmaiCategory.ofRaw(it.toInt())
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          NosmaiNsfwVerdict.ofRaw(it.toInt())
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          NosmaiNsfwClass.ofRaw(it.toInt())
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          NosmaiTextCategory.ofRaw(it.toInt())
        }
      }
      133.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          NosmaiTextLayer.ofRaw(it.toInt())
        }
      }
      134.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          NosmaiModel.ofRaw(it.toInt())
        }
      }
      135.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          NosmaiObjectDetection.fromList(it)
        }
      }
      136.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          NosmaiResult.fromList(it)
        }
      }
      137.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          NosmaiVideoFlag.fromList(it)
        }
      }
      138.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          NosmaiVideoResult.fromList(it)
        }
      }
      139.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          NosmaiTextResult.fromList(it)
        }
      }
      140.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          NosmaiInitResult.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is NosmaiCategory -> {
        stream.write(129)
        writeValue(stream, value.raw)
      }
      is NosmaiNsfwVerdict -> {
        stream.write(130)
        writeValue(stream, value.raw)
      }
      is NosmaiNsfwClass -> {
        stream.write(131)
        writeValue(stream, value.raw)
      }
      is NosmaiTextCategory -> {
        stream.write(132)
        writeValue(stream, value.raw)
      }
      is NosmaiTextLayer -> {
        stream.write(133)
        writeValue(stream, value.raw)
      }
      is NosmaiModel -> {
        stream.write(134)
        writeValue(stream, value.raw)
      }
      is NosmaiObjectDetection -> {
        stream.write(135)
        writeValue(stream, value.toList())
      }
      is NosmaiResult -> {
        stream.write(136)
        writeValue(stream, value.toList())
      }
      is NosmaiVideoFlag -> {
        stream.write(137)
        writeValue(stream, value.toList())
      }
      is NosmaiVideoResult -> {
        stream.write(138)
        writeValue(stream, value.toList())
      }
      is NosmaiTextResult -> {
        stream.write(139)
        writeValue(stream, value.toList())
      }
      is NosmaiInitResult -> {
        stream.write(140)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}


/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface NosmaiModerationApi {
  /**
   * Validates the license and loads ONLY the requested [models]. A model you do
   * not pass never loads. Runs on a background thread natively.
   */
  fun initialize(licenseKey: String, models: List<NosmaiModel>, callback: (Result<NosmaiInitResult>) -> Unit)
  /**
   * Loads the chat text-moderation model. Optional — call only if you moderate
   * text.
   */
  fun initializeText(callback: (Result<Boolean>) -> Unit)
  /** Moderates a single image file (objects + NSFW). */
  fun analyzeImage(filePath: String, callback: (Result<NosmaiResult>) -> Unit)
  /** Moderates a recorded video, sampling one frame per [frameIntervalMs]. */
  fun analyzeVideo(filePath: String, frameIntervalMs: Long, callback: (Result<NosmaiVideoResult>) -> Unit)
  /** Moderates a chat message (Layer-1 blocklist + Layer-2 toxicity model). */
  fun moderateText(message: String, callback: (Result<NosmaiTextResult>) -> Unit)
  /** Overrides an object-detector confidence threshold (0..1). */
  fun setThreshold(category: NosmaiCategory, value: Double)
  /** Overrides an NSFW decision threshold (explicit -> BLOCK, sexy -> WARN). */
  fun setNsfwThreshold(nsfwClass: NosmaiNsfwClass, value: Double)
  /** Releases the engine and frees memory. */
  fun shutdown()

  companion object {
    /** The codec used by NosmaiModerationApi. */
    val codec: MessageCodec<Any?> by lazy {
      MessagesPigeonCodec()
    }
    /** Sets up an instance of `NosmaiModerationApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: NosmaiModerationApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.nosmai_moderation_sdk.NosmaiModerationApi.initialize$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val licenseKeyArg = args[0] as String
            val modelsArg = args[1] as List<NosmaiModel>
            api.initialize(licenseKeyArg, modelsArg) { result: Result<NosmaiInitResult> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.nosmai_moderation_sdk.NosmaiModerationApi.initializeText$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.initializeText{ result: Result<Boolean> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.nosmai_moderation_sdk.NosmaiModerationApi.analyzeImage$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val filePathArg = args[0] as String
            api.analyzeImage(filePathArg) { result: Result<NosmaiResult> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.nosmai_moderation_sdk.NosmaiModerationApi.analyzeVideo$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val filePathArg = args[0] as String
            val frameIntervalMsArg = args[1] as Long
            api.analyzeVideo(filePathArg, frameIntervalMsArg) { result: Result<NosmaiVideoResult> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.nosmai_moderation_sdk.NosmaiModerationApi.moderateText$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val messageArg = args[0] as String
            api.moderateText(messageArg) { result: Result<NosmaiTextResult> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.nosmai_moderation_sdk.NosmaiModerationApi.setThreshold$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val categoryArg = args[0] as NosmaiCategory
            val valueArg = args[1] as Double
            val wrapped: List<Any?> = try {
              api.setThreshold(categoryArg, valueArg)
              listOf(null)
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.nosmai_moderation_sdk.NosmaiModerationApi.setNsfwThreshold$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val nsfwClassArg = args[0] as NosmaiNsfwClass
            val valueArg = args[1] as Double
            val wrapped: List<Any?> = try {
              api.setNsfwThreshold(nsfwClassArg, valueArg)
              listOf(null)
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.nosmai_moderation_sdk.NosmaiModerationApi.shutdown$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.shutdown()
              listOf(null)
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
